name: Publish And Deploy Docs

on:
  push:
    branches: ['master']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # 获取代码

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 设置 node 版本
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci # 安装依赖

      - name: Run tests
        run: npm test # 运行测试，确保代码没有问题

      - name: Publish to npm
        run: npm publish # 发布到 npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 使用 npm token 进行身份验证

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create release tag
        run: |
          git config user.name "lanten"
          git config user.email "lanten233@qq.com"
          git tag "release/$VERSION"
          git push origin "release/$VERSION"

  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build:docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-docs
